# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-22 19:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_dataset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='graph',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
