# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0006_auto_20190224_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='dataset',
        ),
        migrations.AddField(
            model_name='node',
            name='data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datastore.Data'),
            preserve_default=False,
        ),
    ]
