# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_auto_20190224_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
