# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_data_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='kind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edge',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='nid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.TextField(),
        ),
    ]
